### ISSUE TITLE
npm install fails on grunt-contrib-imagemin dependency

### ISSUE THREAD

**Issue by stevenweaver** [PhyloCanvas/PhyloCanvas#26]
```
~/datamonkey/PhyloCanvas git:(master) npm install
npm WARN package.json grunt-contrib-htmlmin@0.1.3 No README data
 
> pngquant-bin@0.1.7 postinstall /home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin
> node index.js

✓ pre-build test passed successfully
 
> optipng-bin@0.3.11 postinstall /home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin
> node index.js

✔ pre-build test passed successfully!
 
> jpegtran-bin@0.2.8 postinstall /home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin
> node index.js

 
> gifsicle@0.1.7 postinstall /home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle
> node index.js

⚠ pre-build test failed, compiling from source...
-
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid tar file
    at Extract.Parse._startEntry (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:47:8)
    at BlockStream.emit (events.js:95:17)
    at BlockStream._emitChunk (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/extract.js:57:8)
    at DirWriter.emit (events.js:92:17)
    at /home/sweaver/datamonkey/PhyloCanvas/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/dir-writer.js:39:8
npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
npm ERR! This is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/sweaver/datamonkey/PhyloCanvas
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sweaver/datamonkey/PhyloCanvas/npm-debug.log
npm ERR! not ok code 0
```

**Comment by richardgoater** [comment]
Hi @stevenweaver, 

thanks very much for raising this issue and I sincerely apologise for the lack of response. I've been working on PhyloCanvas since January and our current thinking is to move away from Grunt as a build tool and use npm scripts, rendering your issue (and associated pull request) obsolete. We're looking to create a community around the library this year so please do consider contributing again.

best,
Richard
